# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
<<<<<<< HEAD
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
=======
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

>>>>>>> 2440b1bf35acae6b8b396cb806c1db016b0211e5
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
<<<<<<< HEAD
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases//

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
=======
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
>>>>>>> 2440b1bf35acae6b8b396cb806c1db016b0211e5
